[package]
name = 'vctrsrs'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'vctrsrs'


[dependencies]
extendr-api = { version = "0.7.1", features = ["either"] }
extendr-vctrs = {path = "../../../rust/extendr-vctrs"}