# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_vctrsrs_wrappers", use_symbols = TRUE, package_name = "vctrsrs")

#' @usage NULL
#' @useDynLib vctrsrs, .registration = TRUE
NULL

#' @export
new_usize_vec <- function(x) .Call(wrap__new_usize_vec, x)

#' @export
format.vec_usize <- function(x) .Call(wrap__show_vec_usize, x)

#' @export
length.vec_usize <- function(x) .Call(wrap__length_vec_usize, x)

#' @export
`[.vec_usize` <- function(x, idx) .Call(wrap__subset_vec_usize, x, idx)

#' @export
c.vec_usize <- function(x, y) .Call(wrap__extend_vec_usize, x, y)


# nolint end
