# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_vctrsrs_wrappers", use_symbols = TRUE, package_name = "vctrsrs")

#' @docType package
#' @usage NULL
#' @useDynLib vctrsrs, .registration = TRUE
NULL

tst_show <- function() .Call(wrap__tst_show)

tst_len <- function() .Call(wrap__tst_len)

tst_subset <- function() .Call(wrap__tst_subset)

tst_trait <- function() invisible(.Call(wrap__tst_trait))

test_mask <- function() invisible(.Call(wrap__test_mask))

VecUsize <- new.env(parent = emptyenv())

VecUsize$new <- function(robj) .Call(wrap__VecUsize__new, robj)

#' @export
`$.VecUsize` <- function (self, name) { func <- VecUsize[[name]]; environment(func) <- environment(); func }

#' @export
`[[.VecUsize` <- `$.VecUsize`


# nolint end
