# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_vctrsrs_wrappers", use_symbols = TRUE, package_name = "vctrsrs")

#' @usage NULL
#' @useDynLib vctrsrs, .registration = TRUE
NULL

new_usize_vec <- function(x) .Call(wrap__new_usize_vec, x)

from_vec_usize <- function(x) .Call(wrap__from_vec_usize, x)


# nolint end
